"""Initial schema with users sources proxies

Revision ID: 98867adc7088
Revises: 
Create Date: 2026-01-11 22:58:56.879192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98867adc7088'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_provider_id', 'users', ['oauth_provider', 'oauth_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.create_table('proxy_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_scraped', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('is_admin_source', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_sources_enabled'), 'proxy_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_proxy_sources_id'), 'proxy_sources', ['id'], unique=False)
    op.create_index(op.f('ix_proxy_sources_url'), 'proxy_sources', ['url'], unique=True)
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('speed_mbps', sa.Float(), nullable=True),
    sa.Column('uptime_percent', sa.Float(), nullable=True),
    sa.Column('anonymity', sa.String(length=20), nullable=True),
    sa.Column('proxy_type', sa.String(length=20), nullable=True),
    sa.Column('can_access_google', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_failures', sa.Integer(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['proxy_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_anonymity'), 'proxies', ['anonymity'], unique=False)
    op.create_index(op.f('ix_proxies_country_code'), 'proxies', ['country_code'], unique=False)
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_index(op.f('ix_proxies_is_working'), 'proxies', ['is_working'], unique=False)
    op.create_index(op.f('ix_proxies_latency_ms'), 'proxies', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_proxies_protocol'), 'proxies', ['protocol'], unique=False)
    op.create_index(op.f('ix_proxies_quality_score'), 'proxies', ['quality_score'], unique=False)
    op.create_index(op.f('ix_proxies_url'), 'proxies', ['url'], unique=True)
    op.create_table('validation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('anonymity', sa.String(length=20), nullable=True),
    sa.Column('can_access_google', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_history_id'), 'validation_history', ['id'], unique=False)
    op.create_index(op.f('ix_validation_history_proxy_id'), 'validation_history', ['proxy_id'], unique=False)
    op.create_index(op.f('ix_validation_history_validated_at'), 'validation_history', ['validated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_history_validated_at'), table_name='validation_history')
    op.drop_index(op.f('ix_validation_history_proxy_id'), table_name='validation_history')
    op.drop_index(op.f('ix_validation_history_id'), table_name='validation_history')
    op.drop_table('validation_history')
    op.drop_index(op.f('ix_proxies_url'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_quality_score'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_protocol'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_latency_ms'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_is_working'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_country_code'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_anonymity'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_proxy_sources_url'), table_name='proxy_sources')
    op.drop_index(op.f('ix_proxy_sources_id'), table_name='proxy_sources')
    op.drop_index(op.f('ix_proxy_sources_enabled'), table_name='proxy_sources')
    op.drop_table('proxy_sources')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_oauth_provider_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
