"""Add scraping sessions and background tasks tables

Revision ID: 9f610160ba2b
Revises: 3ee140dfb02a
Create Date: 2026-01-16 04:36:01.237349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f610160ba2b'
down_revision: Union[str, None] = '3ee140dfb02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_background_task_status_scheduled', 'background_tasks', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_background_tasks_id'), 'background_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_background_tasks_scheduled_for'), 'background_tasks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    op.create_table('scraping_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('scraping_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proxies_found', sa.Integer(), nullable=True),
    sa.Column('proxies_valid', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['proxy_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraping_session_status_source', 'scraping_sessions', ['status', 'source_id'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_id'), 'scraping_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_initiated_by'), 'scraping_sessions', ['initiated_by'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_source_id'), 'scraping_sessions', ['source_id'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_started_at'), 'scraping_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_status'), 'scraping_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_sessions_status'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_started_at'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_source_id'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_initiated_by'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_id'), table_name='scraping_sessions')
    op.drop_index('idx_scraping_session_status_source', table_name='scraping_sessions')
    op.drop_table('scraping_sessions')
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_scheduled_for'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_id'), table_name='background_tasks')
    op.drop_index('idx_background_task_status_scheduled', table_name='background_tasks')
    op.drop_table('background_tasks')
    # ### end Alembic commands ###
