"""add_candidate_sources_table

Revision ID: b5d1f9866721
Revises: 92afc781690f
Create Date: 2026-01-13 14:21:12.983550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d1f9866721'
down_revision: Union[str, None] = '92afc781690f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('discovery_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('proxies_found_count', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_status_score', 'candidate_sources', ['status', 'confidence_score'], unique=False)
    op.create_index(op.f('ix_candidate_sources_confidence_score'), 'candidate_sources', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_candidate_sources_domain'), 'candidate_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_candidate_sources_id'), 'candidate_sources', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_sources_status'), 'candidate_sources', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_sources_url'), 'candidate_sources', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_sources_url'), table_name='candidate_sources')
    op.drop_index(op.f('ix_candidate_sources_status'), table_name='candidate_sources')
    op.drop_index(op.f('ix_candidate_sources_id'), table_name='candidate_sources')
    op.drop_index(op.f('ix_candidate_sources_domain'), table_name='candidate_sources')
    op.drop_index(op.f('ix_candidate_sources_confidence_score'), table_name='candidate_sources')
    op.drop_index('idx_candidate_status_score', table_name='candidate_sources')
    op.drop_table('candidate_sources')
    # ### end Alembic commands ###
